apiVersion: v1
kind: Deployment
metadata:
    name: test-deployment
spec:
    replicas: 1
    template:
        metadata:
          labels:
            app: hello-app
        spec:
          containers:
            - image: strm/helloworld-http
              name: hello-world
              ports:
                - containerPort: 80