apiVersion: v1
kind: Service
metadata:
    name: test-deployment-np
spec:
    selector:
        app: hello-app
    type: NodePort
    ports:
        port: 80
        protocol: TCP
        targetPort: 80