name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build-and-push:

    runs-on: ubuntu-20.04

    steps:
    - name: Check repository
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker image
      run: docker build . -f lab1_extra/new.Dockerfile -t megymikei/hello-app

    - name: Push docker image
      run: docker push megymikei/hello-app
