name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file lab1_extra/new.Dockerfile --tag hello-app-image:$(date +%s)
