name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build-and-push:

    runs-on: self-hosted

    steps:
    - name: Check repository
      uses: actions/checkout@v3

    - name: Import Secrets
      uses: hashicorp/vault-action@v2
      with:
        url: http://127.0.0.1:8200
        tlsSkipVerify: true
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          secret/data/dockerhub DOCKERHUB_USERNAME ;
          secret/data/dockerhub DOCKERHUB_TOKEN ;

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build docker image
      run: docker build . -f $GITHUB_WORKSPACE\ITMO_cloud_systems\ITMO_cloud_systems\lab1_extra\new.Dockerfile -t megymikei/hello-app

    - name: Push docker image
      run: docker push megymikei/hello-app
